<header id="photo_banniere">
	<nav class="navbar navbar-expand-md bg-dark navbar-dark dropdown-menu-right">
		<!-- Brand -->
		<a class="navbar-brand" href="#">Membre</a>

		<!-- Toggler/collapsibe Button -->
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
		<span class="navbar-toggler-icon"></span>
		</button>

		<!-- Navbar links -->
		<div class="collapse navbar-collapse" id="collapsibleNavbar">
			<ul class="navbar-nav">
				<li class="nav-item">
					<a class="nav-link" href="#">Mes photos</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="#">Suggestions</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="mvc/controller/utilisateur/c_deconnexion.php">Déconnexion</a>
				</li> 
			</ul>
		</div> 
	</nav>	
	<div id="logo_membre"></div>
</header>
